### PR TITLE
Allow making changes to the base section in yum-cron and yum-cron-hourly

### PR DESCRIPTION
**Pull request by martbhell**
Hi!

My use for this is so I can add an exclude=java*

Some java apps don't like to have java upgraded underneath their feet.

### CODE REVIEW

**Comment by jeffwidman** [comment]
Thanks!

**Comment by jeffwidman** [comment]
BTW, @martbhell let me know if you're interested in having commit rights to this repo. I still use/maintain the role, but I'm comfortable giving you access rights as well so that you don't have to wait on me to merge stuff like this...

**Comment by martbhell** [comment]
Thanks! Well if you want I can be. Never know when it might come in handy even if I don't have any grand ideas right now :)

**Comment by jeffwidman** [comment]
Added. I feel like having grand ideas might actually be a bad thing for this particular project. Since it's an Ansible role that installs a basic linux utility, I prefer that it be boring and predictable :-). Bug fixes and small enhancements (such as this PR) are all that's really needed.

**Pull request merged**
